version: 2

run:
  timeout: 5m
  tests: true
  go: '1.23'

linters:
  enable:
    # Critical - Catches bugs
    # Note: errcheck disabled due to Terraform provider patterns (d.Set, d.SetId don't need checking)
    - govet             # Go vet issues
    - staticcheck       # Advanced static analysis
    - ineffassign       # Ineffectual assignments
    - unused            # Unused code

    # Code quality - Easy wins
    - misspell          # Spelling mistakes
    - unconvert         # Unnecessary conversions
    - wastedassign      # Wasted assignments

    # Best practices - Low friction
    - errname           # Error naming conventions
    - errorlint         # Error wrapping issues
    - nilerr            # Returning nil with non-nil error

    # Terraform-specific value
    - bodyclose         # HTTP body close (API calls)
    - copyloopvar       # Loop variable capture (replaces exportloopref)
    - sqlclosecheck     # Resource leak detection

  disable:
    # Terraform provider patterns make these noisy
    - errcheck          # d.Set() and d.SetId() don't need error checking in TF providers

    # Too opinionated for existing codebases
    - revive
    - varnamelen
    - nlreturn
    - wsl

    # Would break compatibility
    - interfacebloat
    - ireturn
    - nonamedreturns

  settings:
    staticcheck:
      checks : ["all","-S1009", "-SA9003", "-ST1000", "-ST1003", "-ST1016", "-ST1020", "-ST1021", "-ST1022", "-ST1023"]  # Disable S1009: explicit nil checks improve code readability

linters-settings:
  govet:
    enable-all: true
    disable:
      - shadow  # Too noisy for existing code
      - fieldalignment  # Breaks backwards compatibility

issues:
  exclude-rules:
    # Allow complexity and unused code in test files
    - path: '.*_test\.go$'
      linters:
        - funlen
        - gocyclo
        - unused

    # Allow longer functions in resource files (common pattern)
    - path: resource_alkira_.*\.go
      linters:
        - funlen
        - gocyclo
        - maintidx

    # Legacy code - will fix incrementally
    - path: alkira/
      linters:
        - gocritic
      text: "commentFormatting"

  max-issues-per-linter: 0
  max-same-issues: 0

  # Show all issues for new code
  new: false

  # But allow fixing incrementally
  fix: false
