---
# generated by https://github.com/hashicorp/terraform-plugin-docs
page_title: "alkira_connector_ipsec Resource - terraform-provider-alkira"
subcategory: ""
description: |-
  Manage IPSec Connector.
---

# alkira_connector_ipsec (Resource)

Manage IPSec Connector.


## VPN Mode

`vpn_mode` could be either `ROUTE_BASED` or `POLICY_BASED`. When it's
defined as `ROUTE_BASED`, `routing_options` block is required. When
it's defined as `POLICY_BASED`, `policy_options` block is required.


## Example Usage

```terraform
#
# Create a segment
#
resource "alkira_segment" "segment1" {
  name = "seg1"
  asn  = "65513"
  cidr = "10.16.1.0/24"
}

#
# Create a group
#
resource "alkira_group" "group1" {
  name        = "group1"
  description = "group1"
}

#
# Create IPSec connector and attach it with one segment and group.
#
resource "alkira_connector_ipsec" "test" {
  name           = "test"
  cxp            = "US-WEST"
  group          = alkira_group.group1.name
  segment_id     = alkira_segment.segment1.id
  size           = "SMALL"

  vpn_mode       = "ROUTE_BASED"

  routing_options {
    type = "DYNAMIC"
    customer_gateway_asn = "65310"
  }
}
```

<!-- schema generated by tfplugindocs -->
## Schema

### Required

- **cxp** (String) The CXP where the connector should be provisioned.
- **name** (String) The name of the connector.
- **segment_id** (Number) The ID of the segment associated with the connector.
- **size** (String) The size of the connector. one of `SMALL`, `MEDIUM` and `LARGE`.
- **vpn_mode** (String) The connector can be configured either in `ROUTE_BASED` or `POLICY_BASED`.

### Optional

- **billing_tag_ids** (List of Number) IDs of Billing Tag associated with the connector.
- **endpoint** (Block Set) The endpoint. (see [below for nested schema](#nestedblock--endpoint))
- **group** (String) The group of the connector.
- **id** (String) The ID of this resource.
- **policy_options** (Block Set) Policy options, both on-prem and cxp prefix list IDs must be provided if vpnMode is `POLICY_BASED` (see [below for nested schema](#nestedblock--policy_options))
- **routing_options** (Block Set) Routing options, type is `STATIC`, `DYNAMIC`, or `BOTH` must be provided if `vpn_mode` is `ROUTE_BASED` (see [below for nested schema](#nestedblock--routing_options))
- **segment_options** (Block Set) Additional options for each segment associated with the connector (see [below for nested schema](#nestedblock--segment_options))

<a id="nestedblock--endpoint"></a>
### Nested Schema for `endpoint`

Required:

- **customer_gateway_ip** (String) The IP address of the customer gateway.
- **name** (String) The name of the endpoint.

Optional:

- **advanced** (Block Set) (see [below for nested schema](#nestedblock--endpoint--advanced))
- **preshared_keys** (List of String) An array of presharedKeys, one per tunnel.
- **enableTunnelRedundancy** (Boolean) The enableTunnelRedundancy indicates to Alkira that health for the site should be reported as good as long as any one of the tunnels is up.

<a id="nestedblock--endpoint--advanced"></a>
### Nested Schema for `endpoint.advanced`

Required:

- **dpd_delay** (String) Interval to check the liveness of a peer.
- **dpd_timeout** (String) Timeouts to check the liveness of a peer. IKEv1 only.
- **esp_dh_group_numbers** (String)
- **esp_encryption_algorithms** (String)
- **esp_integrity_algorithms** (String)
- **esp_life_time** (Number) Maximum IPsec ESP lifetime if the IPsec ESP does not rekey.
- **esp_random_time** (String)
- **esp_rekey_time** (String)
- **ike_dh_group_numbers** (String) Diffie Hellman groups to use for IKE SA, one of `MODP1024`, `MODP2048`, `MODP3072`, `MODP4096`, `MODP6144`, `MODP8192`, `ECP256`, `ECP384`, `ECP521`, `CURVE25519`
- **ike_encryption_algorithms** (String) Encryption algorithms to use for IKE SA, one of `AES256CBC`, `AES192CBC`, `AES128CBC`.
- **ike_integrity_algorithms** (String) Integrity algorithms to use for IKE SA, one of `SHA1`, `SHA256`, `SHA384`, `SHA512`.
- **ike_over_time** (Number) Maximum IKE SA lifetime if the IKE SA does not rekey.
- **ike_random_time** (Number) Time range from which to choose a random value to subtract from rekey times.
- **ike_rekey_time** (Number) IKE tunnel rekey time.
- **ike_version** (String) IKE version, either `IKEv1` or `IKEv2`
- **initiator** (String)
- **local_auth_type** (String) Local-ID type - IKE identity to use for authentication round, one of `FQDN`, `USER_FQDN`, `KEYID`, `IP_ADDR`.
- **local_auth_value** (String) Local-ID value.
- **remote_auth_type** (String) Remote-ID type - IKE identity to use for authentication round, one of `FQDN`, `USER_FQDN`, `KEYID`, `IP_ADDR`.
- **remote_auth_value** (String) Remote-ID value.
- **replay_window_size** (Number) IPsec replay window for the IPsec SA.



<a id="nestedblock--policy_options"></a>
### Nested Schema for `policy_options`

Required:

- **cxp_prefix_list_ids** (List of Number) CXP Prefix List IDs.
- **on_prem_prefix_list_ids** (List of Number) On Prem Prefix List IDs.


<a id="nestedblock--routing_options"></a>
### Nested Schema for `routing_options`

Required:

- **type** (String) Routing type, one of `STATIC`, `DYNAMIC`, or `BOTH`.

Optional:

- **availability** (String) The method to determine the availability of static route. The value could be `IKE_STATUS` or `IPSEC_INTERFACE_PING`.
- **customer_gateway_asn** (String) The customer gateway ASN to use for dynamic route propagation.
- **prefix_list_id** (Number) The ID of prefix list to use for static route propagation.


<a id="nestedblock--segment_options"></a>
### Nested Schema for `segment_options`

Required:

- **name** (String) Segment Name.

Optional:

- **disable_advertise_on_prem_routes** (Boolean) Additional options for each segment associated with the connector.
- **disable_internet_exit** (Boolean) Enable or disable access to the internet when traffic arrives via this connector.


