name: acceptance-test-preprod-key

# Only trigger, when the normal acceptance test passed
on:
  workflow_run:
    workflows: ["acceptance-test-preprod"]
    types:
      - completed
env:
  ALKIRA_API_KEY: ${{ secrets.PREPROD_TERRAFORM_API_KEY }}

jobs:
  acceptance-test-preprod-key:
    runs-on: ubuntu-latest

    steps:
      -
        name: Pull Terraform CLI
        uses: hashicorp/setup-terraform@v2
      -
        name: Add .terraformrc
        run: echo 'provider_installation {
                    dev_overrides {
                    "alkiranet/alkira" = "/home/runner/work/terraform-provider-alkira/terraform-provider-alkira/bin"
                    }
                    direct {}
                  }' > ~/.terraformrc
      -
        name: Checkout Repo
        uses: actions/checkout@v3
      -
        name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20
      -
        name: Build Terraform Provider
        run: |
          cd /home/runner/work/terraform-provider-alkira/terraform-provider-alkira
          make
      -
        name: Run Terraform Apply
        run: |
          cd acceptance
          terraform apply --auto-approve
      -
        name: Run Terraform Destroy
        if: ${{ always() }}
        run: |
          cd acceptance
          terraform destroy --auto-approve
