name: acceptance-test-prod

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

env:
  ALKIRA_PORTAL:   ${{ secrets.PROD_TERRAFORM_PORTAL }}
  ALKIRA_USERNAME: ${{ secrets.PROD_TERRAFORM_USERNAME }}
  ALKIRA_PASSWORD: ${{ secrets.PROD_TERRAFORM_PASSWORD }}
  ALKIRA_CXP:      "US-WEST"

jobs:
  acceptance-test-prod:
    runs-on: ubuntu-latest

    steps:
      -
        name: Pull Terraform CLI
        uses: hashicorp/setup-terraform@v3
      -
        name: Add .terraformrc
        run: echo 'provider_installation {
                    dev_overrides {
                    "alkiranet/alkira" = "/home/runner/work/terraform-provider-alkira/terraform-provider-alkira/bin"
                    }
                    direct {}
                  }' > ~/.terraformrc
      -
        name: Checkout Repo
        uses: actions/checkout@v4
      -
        name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      -
        name: Build Terraform Provider
        run: |
          cd /home/runner/work/terraform-provider-alkira/terraform-provider-alkira
          make
      -
        name: Run Terraform Apply
        run: |
          cd acceptance
          terraform apply --auto-approve -var cxp=$ALKIRA_CXP
      -
        name: Run Terraform Destroy
        if: ${{ always() }}
        run: |
          cd acceptance
          terraform destroy --auto-approve
