# This is a basic workflow to help you get started with Actions

name: Acceptance Test CI

# Controls when the workflow will run
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  acceptance_test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - 
        name: Pull Terraform CLI
        uses: hashicorp/setup-terraform@v2
      -
        name: Checkout Repo
        uses: actions/checkout@v3
      -
        name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
