name: latest
on:
  push:
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_S3_DOWNLOADS_DEV_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_DOWNLOADS_DEV_SECRET_KEY }}
  AWS_REGION: us-east-1
  BUILD_DIR: /home/runner/work/terraform-provider-alkira/terraform-provider-alkira
  BUILD_ARTIFACTS_PATH: s3://downloads.alkira.com/dev/terraform-provider-alkira

jobs:
  latest:
    name: latest
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build Terraform Provider
        run: |
          cd ${{ env.BUILD_DIR }}
          make release

      - name: Upload to Latest
        run: |
          ls "${{ env.BUILD_DIR }}"
          ls "${{ env.BUILD_DIR }}/releases/"
          for file in "${{ env.BUILD_DIR }}/releases/*/*.tar.gz"; do
            aws s3 cp "$file" "${{ env.BUILD_ARTIFACTS_PATH }}/"
          done
