name: latest
on:
  push:
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_S3_DOWNLOADS_DEV_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_DOWNLOADS_DEV_SECRET_KEY }}
  AWS_REGION: us-east-1
  BUILD_DIR: /home/runner/work/terraform-provider-alkira/terraform-provider-alkira
  BUILD_ARTIFACTS_PATH: s3://downloads.alkira.com/dev/terraform-provider-alkira/latest

jobs:
  latest:
    name: latest
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Golang
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build terraform provider
        run: |
          cd ${{ env.BUILD_DIR }}
          make release

      - name: Upload to S3 latest directory
        run: |
          ver=`ls "${{ env.BUILD_DIR }}/releases/"`
          aws s3 rm "${{ env.BUILD_ARTIFACTS_PATH }}/" --recursive
          aws s3 cp releases/$ver "${{ env.BUILD_ARTIFACTS_PATH }}/" --recursive

