name: unit-test
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - main
      - dev

env:
  BUILD_DIR: /home/runner/work/terraform-provider-alkira/terraform-provider-alkira
  CGO_ENABLED: 0

jobs:
  latest:
    name: latest
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Golang
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Run unit test terraform provider
        run: |
          cd ${{ env.BUILD_DIR }}
          make test
